### ISSUE TITLE
nblue noth dead

### ISSUE THREAD

**Issue by jalavoui** [Zormeister/NootedBlue#18]
Hi Zormeister

idk if you are aware but there is progress with nblue. check on insanlymac
current binary is working for some users.

hope you have the hardware to keep this going

**Comment by Zormeister** [comment]
i kindof do?

i have other areas of hardware such as WiFi to cover, since you know, macOS without an internet connection is pure torture, same goes for no graphics acceleration

HP and their BIOS whitelists, am I right?

if i feel like it, it'll get resurrected from the grave, or if i get stuck with an intel machine, lol.

a friend of mine has some Tiger Lake hardware, though, i'm pretty sure they haven't installed macOS

anyways, i'm not saying that the upstream project is out of limbo, but it certainly won't get any major changes
